### ISSUE TITLE
[QUESTION] Can this be used to generate custom-only docker compose configs, or do we have to use a predefined template for it to work?

### ISSUE THREAD

**Issue by teward** [compose-generator/compose-generator#431]
Currently, I understand we can use 'custom' backends, etc. in the prompt by choosing custom services and defining the Docker image to pull, env vars, network exposure, etc.

However, I am encountering the issue that if you *only* are working with a custom service definition and no other templated service definitions the program hard-errors on "No templates selected." and aborts.

Is this by-design?  Or is this a bug?  (If this is a bug I'll re-file as a Bug type issue and follow your layout/template)

**Comment by marcauberer** [comment]
Hi @teward. That sounds like a bug to me ...

**Comment by teward** [comment]
I'll file a bug then on this, thanks.
