### ISSUE TITLE
Dynamic Generation of compose files instead of templates

### ISSUE THREAD

**Issue by tschuehly** [compose-generator/compose-generator#5]
Instead of having templates for predefined stacks, a dynamic approach would be much more efficent.

We have several questions when generating a docker-compose
1. Is it a dev or production enviroment?

>  Include nginx reverse proxy: jwilder/nginx-proxy , include let's encry: jrcs/letsencrypt-nginx-proxy-companion

2. Do you want a frontend? Which one?

> Angular / React / Vue -> does frontend exist? no -> run create-react-app / npx create-next-app / ng new

3. What Backend do you want to use?

> Spring / Node / PHP / Rust -> does backend exist? no -> run sprinig initializer / ...

3. What DB you want to use?

> Postgres / MariaDB / Mongo / H2 / ....

4. Do you want a DB Admin tool

> Phpmyadmin, pgAdmin

**Comment by marcauberer** [comment]
The database admin tool depends directly on the db, that was selected. Maybe we can solve this more efficient ...

**Comment by tschuehly** [comment]
> The database admin tool depends directly on the db, that was selected. Maybe we can solve this more efficient ...

Yes that's why the question is if you want one, then the appropriate is selected

**Comment by marcauberer** [comment]
I just dropped the first commit for this feature in the `feature/dynamic-stacks` branch. I'd appreciate you to check if you think this might work out. I am open for feedback

**Comment by marcauberer** [comment]
Dynamic stacks are included in v0.5.0 and will be extended in the future. I think this issue can be closed ...
